#!/bin/bash
# ReactOS BuildBot Build Scripts for Linux
# clean - Get our working copy back to a defined state. (no output, all modules disabled)
source ../../config.inc

# Disable additional modules
rm -rf modules/optional
rm -rf modules/rostests_disabled
mv modules/rostests modules/rostests_disabled 2>/dev/null

# Clean the working directory
if [ -d "$WORKDIR" ]; then
	cd "$WORKDIR"
	/usr/local/RosBE/clean.sh
else
	echo "Creating $WORKDIR..."
	mkdir "$WORKDIR"
fi

exit 0
