#!/bin/bash
source ../../config.inc

if [ "$1" = "" ]; then
	echo "Please specify the revision number!"
	exit 1
fi

# If you decide to build a different branch, BuildBot does an "rm -rf" on the whole "build" directory first (which needs to succeed!)
# So recopy our optional modules first.
rm -rf modules/optional
cp -R ../../deps modules/optional

# Enable rostests and build a regression-testing Boot-CD
mv modules/rostests_disabled modules/rostests
../../configure
../../build_reactos bootcdregtest
mv modules/rostests modules/rostests_disabled

# FIXME: Only needed for preserved regtesting ISOs. Uses fixed pathes as well..
mv $ROS_OUTPUT/reactos/bootcdregtest.iso ../../dbgtest_cmake/isos/bootcdregtest-$1.iso
