#!/bin/bash
# ReactOS BuildBot Build Scripts for Linux
# regtestcd - Enable optional and rostests modules and build a bootcdregtest.
#
# Parameter $1 (optional) - If a revision is given here, collect this Test-CD under this revision number
source ../../config.inc

rm -rf modules/rostests
cp -R ../../deps modules/optional
mv -v modules/rostests_disabled modules/rostests

../../configure
ret=$?
if [ $ret -ne 0 ]; then
	exit $ret
fi

../../build_reactos bootcdregtest
ret=$?
if [ $ret -ne 0 ]; then
	exit $ret
fi

if [ "$1" != "" ]; then
	# FIXME: Make this path configurable
	mv $ROS_OUTPUT/reactos/bootcdregtest.iso ../../dbgtest_cmake/isos/bootcdregtest-$1.iso
fi

exit 0
