#!/bin/bash
# ReactOS BuildBot Build Scripts for Linux
# build_host_tools - Build the host tools
source ../../config.inc

$TIME bash -c "(
	if [ -d "$ROS_OUTPUT/host-tools" ]; then
		cd $ROS_OUTPUT/host-tools
		ninja
	fi
)"
