#!/bin/bash
# ReactOS BuildBot Build Scripts
# clean - Get our working copy back to a defined state. (no output, all modules disabled)
#
# Parameter $1 (optional) - If this parameter is given, modules are left untouched.
#                           Only use this for Buildslaves that always build with a module like "rostests" enabled.
source ../../config.inc

if [ "$1" = "" ]; then
	# Disable additional modules
	rm -f reactos/modules/optional
	rm -f reactos/modules/rostests
fi

# Clean the working directory
if [ -d "$ROS_OUTPUT" ]; then
	echo "* Cleaning $ROS_OUTPUT..."
	rm -rf "$ROS_OUTPUT"
fi

exit 0
