#!/bin/bash
# ReactOS BuildBot Build Scripts
# configure - Set up the environment for building and let CMake generate build files.
source ../../config.inc

#
# Default configuration in config.inc is RosBE/GCC-related
# MSVC configuration requires overwrites in builder_config.inc like this:
#
#export INCLUDE="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE;C:\Program Files (x86)\Windows Kits\8.1\include\shared;C:\Program Files (x86)\Windows Kits\8.1\include\um"
#export LIB="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86"
#export LIBPATH="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB"
#export PATH="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/bin/x86:$ROSBE_DIR/bin:/usr/bin:/cygdrive/c/Windows/System32/wbem:/cygdrive/c/Windows/System32"
#export ROS_OUTPUT="$WORKDIR/output-VS-$ROS_ARCH"
#

export REVISION_ID=$1

$TIME bash -c "(
	mkdir -p $ROS_OUTPUT
	cd $ROS_OUTPUT
	mkdir -p reactos

	if [ "$REVISION_ID" -lt "$ROS_NO_HOST_TOOLS_REV" ]; then
		mkdir -p host-tools
		cd host-tools
		rm -f CMakeCache.txt
		cmake -G 'Ninja' -DARCH:STRING=$ROS_ARCH $SOURCEDIR
		cd ..
	fi

	cd reactos
	rm -f CMakeCache.txt
	cmake -G 'Ninja' -DCMAKE_TOOLCHAIN_FILE:FILEPATH=toolchain-msvc.cmake -DARCH:STRING=$ROS_ARCH -DREACTOS_BUILD_TOOLS_DIR:PATH="$ROS_OUTPUT/host-tools" -DRUNTIME_CHECKS:BOOL=0 $SOURCEDIR
)"
