#!/bin/bash
# ReactOS BuildBot Build Scripts
# patching - Patch the tree with the given JIRA attachment ID of the patch file.
#
# Parameter $1 - Attachment ID of the patch file
source ../../config.inc

try_patch()
{
	svn patch --non-interactive --dry-run default.patch | tee check.txt || return 1

	if grep -q "Summary of conflicts:" check.txt; then
		echo "Applying patch failed!"
		return 1
	fi
	
	return 0
}

if [ "$1" = "" ]; then
	echo "Skipping patch phase"
	exit 0
fi

echo "* Downloading patch."
wget -q --output-document=default.patch "http://jira.reactos.org/secure/attachment/$1/" || exit $?

if ! grep -q "Index:" default.patch; then
	echo "Not a patch file!"
	exit 1
fi

echo "* Performing a dry-run relative to SVN directory reactos."
cd reactos

if not try_patch; then
	echo "* Performing a dry-run relative to SVN project root."
	cd ..
fi

if not try_patch; then
	echo "Applying patch failed!"
	exit 1
fi

echo "* Applying patch."
svn patch --non-interactive default.patch
