#!/bin/bash
# ReactOS BuildBot Build Scripts
# patching - Patch the tree with the given JIRA attachment ID of the patch file.
#
# Parameter $1 - Attachment ID of the patch file
source ../../config.inc

clean_exit()
{
	# Disable rostests again to restore the defined state of our tree
	mv modules/rostests modules/rostests_disabled 2>/dev/null
	exit $1
}

if [ "$1" = "" ]; then
	echo "Skipping patch phase"
	exit 0
fi

echo "* Downloading patch."
wget -q --output-document=default.patch "http://jira.reactos.org/secure/attachment/$1/" || exit $?

if ! grep -q "Index:" default.patch; then
	echo "Not a patch file!"
	exit 1
fi

# Let's be able to apply patches to modules/rostests
mv modules/rostests_disabled modules/rostests 2>/dev/null

echo "* Performing a dry-run."
svn patch --non-interactive --dry-run default.patch | tee check.txt || clean_exit $?

if grep -q "Summary of conflicts:" check.txt; then
	echo "Applying patch failed!"
	clean_exit 1
fi

echo "* Applying patch."
svn patch --non-interactive default.patch
clean_exit $?
