#!/bin/bash
# ReactOS BuildBot Build Scripts for Linux
# Update the ahk tests checkout, copy the apps and the compiled tests
# Parameter $1 (optional) - SVN Revision number of the AHK tests

AHKTESTS_URL=https://svn.reactos.org/project-tools/trunk/ahk_tests
AHK_DIR=modules/AHK_Tests
AHK_REV=HEAD

if [ $# -eq 1 ] ; then AHK_REV=$1 ; fi
if [ -d $AHK_DIR ] ; then
	svn --non-interactive --no-auth-cache --revision $AHK_REV update $AHK_DIR
else
	svn --non-interactive --no-auth-cache --revision $AHK_REV checkout $AHKTESTS_URL $AHK_DIR
fi
/bin/cp -a -r -f -v ../Apps ../Tests $AHK_DIR
