#!/bin/bash
# ReactOS BuildBot Build Scripts
# regtestcd - Enable optional and rostests modules and build a bootcdregtest.
#
# Parameter $1 - SVN Revision number of the build
# Parameter $2 (optional) - Add this suffix to the created Test-CD and upload it.
# Parameter without_rostests (optional) - Don't build the regression tests
source ../../config.inc

ln -s $SOURCEDIR/../../deps reactos/modules/optional || exit $?
params="${@}"
if [ -n "${params##*without_rostests*}" ] ; then
  ln -s $SOURCEDIR/rostests reactos/modules/rostests || exit $?
fi

../../configure $1 || exit $?
../../build_reactos bootcdregtest || exit $?

if [ "$2" != "" ]; then
	rsync -e "ssh -l $UPLOAD_USER -i $UPLOAD_KEY" $ROS_OUTPUT/reactos/bootcdregtest.iso $UPLOAD_HOST:$UPLOAD_ISODIR/bootcdregtest/bootcdregtest-$2.iso
fi

exit 0
