#!/bin/bash
# ReactOS BuildBot Build Scripts for Linux
# regtestcd - Enable optional and rostests modules and build a bootcdregtest.
#
# Parameter $1 - SVN Revision number of the build
# Parameter $2 (optional) - Add this suffix to the created Test-CD and collect it in $REGTESTCD_DIR
source ../../config.inc

cp -R ../../deps modules/optional || exit $?
mv -v modules/rostests_disabled modules/rostests || exit $?

../../configure $1 || exit $?
../../build_reactos bootcdregtest || exit $?

if [ "$2" != "" ]; then
	mkdir $REGTESTCD_DIR 2>&1 >/dev/null
	mv $ROS_OUTPUT/reactos/bootcdregtest.iso $REGTESTCD_DIR/bootcdregtest-$2.iso
fi

exit 0
