#!/bin/bash
# ReactOS BuildBot Build Scripts
# regtest - Call sysreg on the desired regression-testing ISO
#
# Parameter $1            - If a suffix is given here, this ISO is copied from $REGTESTCD_DIR and tested.
#                           Otherwise, the last built ISO is tested.
# Parameter $2 (optional) - By default, ISOs are kept in $REGTESTCD_DIR. If anything is given here, the ISO to be tested
#                           will be moved out of $REGTESTCD_DIR.
source ../../config.inc

if [ "$1" = "" ]; then
	echo "Please specify the suffix of the ISO to test!"
	exit 1
fi

if [ "$2" = "" ]; then
	CMD=cp
else
	CMD=mv
fi

echo "* Testing bootcdregtest-$1.iso"
$CMD $REGTESTCD_DIR/bootcdregtest-$1.iso bootcdregtest.iso

../../sysreg2 ../sysreg.xml
