#!/bin/bash
# ReactOS BuildBot Build Scripts
# regtest - Call sysreg on the desired regression-testing ISO
#
# Parameter $1 (optional) - The ISO with this suffix is copied from the ISO storage and tested.
source ../../config.inc

ISONAME="bootcdregtest.iso"

if [ "$1" != "" ]; then
	ISONAME="reactos-bootcdregtest-$1.iso"
	wget -q --output-document=bootcdregtest.iso "http://$UPLOAD_HOST/bootcdregtest/$ISONAME" || exit $?
fi

echo "* Testing $ISONAME"
../../sysreg2 ../sysreg.xml
