#!/bin/bash
# ReactOS BuildBot Build Scripts for Linux
# revert - Revert any patches that may have been applied.
source ../../config.inc

process_directory()
{
	local directory="$1"

	# SVN Revert the directory
	svn revert "$directory" -R --non-interactive

	# Clean unknown files
	svn status "$directory" | awk '/^?/{print $2}' | xargs rm -rf
}

if ! [ -e "$SOURCEDIR/COPYING" ]; then
    echo "Exiting, no tree checked out"
    exit 0
fi

process_directory "$SOURCEDIR"
exit 0
