#!/bin/bash
# ReactOS BuildBot Build Scripts
# vbox_clean - Clean the remainders of a previous VirtualBox session before running regression tests
source ../../config.inc

# Ensure there is a VirtualBox GUI instance
instance=`pgrep VirtualBox | wc -l`
if [ "$instance" -eq "0" ]; then
	echo Starting VirtualBox GUI
	xvfb-run -a /usr/bin/VirtualBox &
	sleep 10s
fi

exit 0
