#!/bin/bash
# ReactOS BuildBot Build Scripts
# clean - Perform all cleanup operations outside the source tree (e.g. the $ROS_OUTPUT build directory)
source ../../config.inc

# Clean the working directory
if [ -d "$ROS_OUTPUT" ]; then
	echo "* Cleaning $ROS_OUTPUT..."
	rm -rf "$ROS_OUTPUT"
fi

exit 0
