#!/bin/bash
# ReactOS BuildBot Build Scripts
# regtestcd - Build and upload a bootcdregtest
#
# Parameters - Additional configuration options directly passed to the configure script.
#              Unless you run other tests (like AHK tests), you should set this to "-DENABLE_ROSTESTS=1"
source ../../config.inc

cp -R $SOURCEDIR/../../deps modules/optional || exit $?
../../configure $@ || exit $?
../../build_reactos bootcdregtest || exit $?

if [ $UPLOAD_REGTESTCD ]; then
	REVISION_SUFFIX=`cat revision_suffix`
	cp $ROS_OUTPUT/bootcdregtest.iso /mnt/bootcdregtest/reactos-bootcdregtest-$REVISION_SUFFIX-$UPLOAD_SUFFIX.iso
fi

exit 0
