#!/bin/bash
# ReactOS BuildBot Build Scripts
# run_rostests - Run the tests built via build_rostests using rosautotest
#
# Parameter $1 - The suffix of the directory containing the tests to run
# Parameter $2 - BuildBot Build number of the ReactOS build that has been tested.
# Parameter $3 - BuildBot "reason" property.
SUFFIX="$1"
BUILDNO="$2"
REASON="$3"
source ../../config.inc

rm -rf "${ROSAUTOTEST_DIR}"
mv "${ROSTESTS_PREFIX}-${SUFFIX}" "${ROSAUTOTEST_DIR}" || exit $?

cd $WORKDIR
mv ${ROSAUTOTEST_DIR}/rosautotest.exe . || exit $?
cp $SOURCEDIR/../rosautotest.ini . || exit $?

COMMENT="Build ${BUILDNO}"
if [ "${REASON}" != "" -a "${REASON}" != "None" ]; then
	COMMENT+=", Reason: ${REASON}"
fi

./rosautotest.exe /c "${COMMENT}" /w

# Initiate a graceful shutdown of the BuildBot worker, which in turn
# initiates a graceful reboot of the Windows VM.
touch $SOURCEDIR/../../shutdown.stamp
