#!/bin/bash
# ReactOS BuildBot Build Scripts
# run_tests - Call the "rostests_install" target to copy all tests to $ROSTESTS_INSTALL and run them using rosautotest
#
# Parameter $1 - The build number to submit to the web service
source ../../config.inc

rm -rf $ROSTESTS_INSTALL
mkdir $ROSTESTS_INSTALL

cd $ROS_OUTPUT
ninja rostests_install

cd $WORKDIR
mv $ROS_OUTPUT/modules/rostests/rosautotest/rosautotest.exe .
cp $SOURCEDIR/../rosautotest.ini .
export ROSAUTOTEST_DIR="$ROSTESTS_INSTALL"
./rosautotest.exe /c "Build $1" /w
