#!/bin/bash
# ReactOS BuildBot Build Scripts
# run_rostests - Run the tests built via build_rostests using rosautotest
#
# Parameter $1 - The suffix of the directory containing the tests to run
source ../../config.inc

rm -rf "${ROSAUTOTEST_DIR}"
mv "${ROSTESTS_PREFIX}-$1" "${ROSAUTOTEST_DIR}" || exit $?

cd $WORKDIR
mv ${ROSAUTOTEST_DIR}/rosautotest.exe . || exit $?
cp $SOURCEDIR/../rosautotest.ini . || exit $?
./rosautotest.exe /c "Build $1" /w
